window.REBUILD_DATA = {
  nav:[
    {id:'today',icon:'◉',label:'Today'},
    {id:'training',icon:'🏋️',label:'Training'},
    {id:'nutrition',icon:'🥗',label:'Nutrition'},
    {id:'progress',icon:'↗',label:'Progress'},
    {id:'plan',icon:'▦',label:'Plan'}
  ],
  onboarding:[
    {id:'mode',q:'Which REBUILD path fits you?',hint:'You can change this later.',type:'choice',options:[['core','Regular — I want to stay fit and keep it simple'],['pro','Pro — I train seriously and want deeper metrics']]},
    {id:'goal',q:'What is your main goal right now?',type:'choice',options:[['fatloss','Lose fat / get lean'],['muscle','Build muscle'],['hybrid','Become more athletic'],['run','Improve running'],['general','General fitness']]},
    {id:'age',q:'How old are you?',type:'number',unit:'years',placeholder:'e.g. 20',hint:'Used later for training and nutrition personalization.'},
    {id:'bodyweight',q:'What is your current bodyweight?',type:'number',unit:'lb',placeholder:'e.g. 180',hint:'Used for starting nutrition and strength recommendations.'},
    {id:'height',q:'What is your height in inches?',type:'number',unit:'in',placeholder:'e.g. 72',hint:'72 inches = 6 feet. We can make this prettier later.'},
    {id:'experience',q:'How experienced are you with lifting?',type:'choice',options:[['new','New'],['some','Some experience'],['experienced','Experienced']]},
    {id:'days',q:'How many days per week can you realistically train?',type:'choice',options:[['3','3 days'],['4','4 days'],['5','5 days'],['6','6 days']]},
    {id:'runlevel',q:'What best describes your current running?',type:'choice',options:[['none','I barely run'],['easy','I can run 1–3 miles'],['steady','I can run 3–6 miles'],['advanced','I run 6+ miles comfortably']]},
    {id:'benchPR',q:'What is your best recent bench press?',type:'number',unit:'lb',placeholder:'e.g. 145',hint:'Use a recent clean 1-rep max or best estimate. Leave blank if unknown.'},
    {id:'squatPR',q:'What is your best recent squat?',type:'number',unit:'lb',placeholder:'e.g. 185',hint:'Use a recent clean 1-rep max or best estimate. Leave blank if unknown.'},
    {id:'deadliftPR',q:'What is your best recent deadlift?',type:'number',unit:'lb',placeholder:'e.g. 225',hint:'Use a recent clean 1-rep max or best estimate. Leave blank if unknown.'},
    {id:'milePR',q:'What is your fastest recent mile?',type:'time',unit:'min:sec',placeholder:'e.g. 8:45',hint:'A recent best is enough. Leave blank if you do not know.'},
    {id:'equipment',q:'Where do you train most?',type:'choice',options:[['gym','Gym'],['home','Home gym'],['mixed','Both']]},
    {id:'schedule',q:'Should REBUILD plan around work, school and other events?',type:'choice',options:[['yes','Yes — build around my life'],['no','No — I will manage timing myself']]},
    {id:'guidance',q:'How much guidance do you want?',type:'choice',options:[['simple','Just tell me what to do'],['teach','Teach me along the way'],['deep','Show me the details too']]}
  ],
  days:[
    {date:'2026-09-07',dow:'Mon',day:7,work:'2:00–6:00 PM',focus:'Upper + Bike',type:'WORK',tasks:[['6:30 AM','🐕','Dog walk','25–30 min • cool pavement'],['7:15 AM','🍳','Breakfast','Protein + carbs'],['8:30 AM','🏋️','Upper Body A','~60 min'],['9:40 AM','🚲','Bike Zone 2','30 min • conversational'],['11:45 AM','🥗','Lunch','Recovery meal'],['1:00 PM','🧠','REBUILD dev','45 min'],['2:00 PM','🧰','Work','2:00–6:00 PM'],['7:00 PM','🍽️','Dinner','Protein + vegetables'],['9:30 PM','📝','Log the day','Weight + notes']]},
    {date:'2026-09-08',dow:'Tue',day:8,work:null,focus:'Lower + Easy Run',type:'OFF',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Fuel the session'],['8:30 AM','🏋️','Lower Body','~55 min • no failure'],['11:45 AM','🥗','Lunch','Protein + carbs'],['1:00 PM','🧠','REBUILD dev','45–60 min'],['5:30 PM','🏃','Easy Run','3.0 mi • conversational'],['7:00 PM','🍽️','Dinner','Recovery meal'],['9:30 PM','📝','Log the day','Quick check-in']]},
    {date:'2026-09-09',dow:'Wed',day:9,work:null,focus:'Full + Row',type:'OFF',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Protein + carbs'],['8:30 AM','🏋️','Full Body','~55 min'],['9:35 AM','🚣','Row Zone 2','30 min'],['11:45 AM','🥗','Lunch','Recovery meal'],['1:00 PM','🧠','REBUILD dev','45–60 min'],['5:30 PM','🤼','Wrestling technique','30–35 min • skill first'],['7:00 PM','🍽️','Dinner','Protein + vegetables']]},
    {date:'2026-09-10',dow:'Thu',day:10,work:'2:00–10:30 PM',focus:'Tempo Run',type:'WORK',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Carbs + protein'],['8:00 AM','🏃','Tempo Run','10 easy + 3×5 min controlled'],['9:15 AM','🧘','Cooldown','10 min mobility'],['11:30 AM','🥗','Lunch','Pre-work meal'],['12:15 PM','🧠','REBUILD dev','30 min'],['2:00 PM','🧰','Work','2:00–10:30 PM'],['6:30 PM','🥪','Packed meal','Eat on break'],['11:00 PM','🌙','Wind down','Hydrate + sleep']]},
    {date:'2026-09-11',dow:'Fri',day:11,work:null,focus:'Upper + Air Bike',type:'OFF',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Protein + carbs'],['8:30 AM','🏋️','Upper Body A','~60 min'],['9:40 AM','🚴','Air Bike Zone 2','30 min'],['11:45 AM','🥗','Lunch','Recovery meal'],['1:00 PM','🧠','REBUILD dev','60 min'],['7:00 PM','🍽️','Dinner','Protein + vegetables']]},
    {date:'2026-09-12',dow:'Sat',day:12,work:null,focus:'Long Run 4.5 mi',type:'LONG',tasks:[['6:15 AM','🍌','Pre-run snack','Easy carbs + water'],['7:00 AM','🏃','Long Run','4.5 mi • easy'],['8:00 AM','🧘','Cooldown','Walk + mobility'],['8:30 AM','🍳','Breakfast','Recovery meal'],['12:30 PM','🥗','Lunch','Carbs + protein'],['3:00 PM','❤️','Date / free time','Optional'],['7:00 PM','🍽️','Dinner','Refuel']]},
    {date:'2026-09-13',dow:'Sun',day:13,work:'12:00–8:30 PM',focus:'Recovery',type:'WORK',tasks:[['6:45 AM','🐕','Dog walk','20–25 min'],['7:30 AM','🍳','Breakfast','Easy morning'],['8:30 AM','🧘','Mobility','20 min'],['9:00 AM','🪢','Jump Rope','Easy technique • optional'],['10:30 AM','🥗','Early lunch','Before work'],['12:00 PM','🧰','Work','12:00–8:30 PM'],['5:00 PM','🥪','Packed meal','Eat on break'],['9:00 PM','📝','Weekly review','5 min only']]},
    {date:'2026-09-14',dow:'Mon',day:14,work:'2:00–10:30 PM',focus:'Lower + Bike',type:'WORK',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Protein + carbs'],['8:30 AM','🏋️','Lower Body','~55 min'],['9:35 AM','🚲','Bike Zone 2','25–30 min'],['11:30 AM','🥗','Lunch','Pre-work meal'],['12:15 PM','🧠','REBUILD dev','30 min'],['2:00 PM','🧰','Work','2:00–10:30 PM'],['6:30 PM','🥪','Packed meal','Eat on break']]},
    {date:'2026-09-15',dow:'Tue',day:15,work:null,focus:'Easy Run + Wrestling',type:'OFF',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Easy morning'],['8:00 AM','🏃','Easy Run','3.5 mi • conversational'],['11:45 AM','🥗','Lunch','Recovery meal'],['1:00 PM','🧠','REBUILD dev','60 min'],['5:30 PM','🤼','Wrestling technique','30–35 min'],['7:00 PM','🍽️','Dinner','Protein + carbs']]},
    {date:'2026-09-16',dow:'Wed',day:16,work:null,focus:'Upper + Row',type:'OFF',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Protein + carbs'],['8:30 AM','🏋️','Upper Body A','~60 min'],['9:40 AM','🚣','Row Zone 2','30 min'],['11:45 AM','🥗','Lunch','Recovery meal'],['1:00 PM','🧠','REBUILD dev','60 min'],['7:00 PM','🍽️','Dinner','Protein + vegetables']]},
    {date:'2026-09-17',dow:'Thu',day:17,work:null,focus:'Tempo Run',type:'OFF',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Carb focused'],['8:00 AM','🏃','Tempo Run','~4 mi total'],['9:00 AM','🧘','Cooldown','Walk + mobility'],['11:45 AM','🥗','Lunch','Recovery meal'],['1:00 PM','🧠','REBUILD dev','60 min'],['7:00 PM','🍽️','Dinner','Protein + vegetables']]},
    {date:'2026-09-18',dow:'Fri',day:18,work:'2:00–10:30 PM',focus:'Full + Air Bike',type:'WORK',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Protein + carbs'],['8:30 AM','🏋️','Full Body','~55 min'],['9:35 AM','🚴','Air Bike Zone 2','25–30 min'],['11:30 AM','🥗','Lunch','Pre-work meal'],['12:15 PM','🧠','REBUILD dev','30 min'],['2:00 PM','🧰','Work','2:00–10:30 PM'],['6:30 PM','🥪','Packed meal','Eat on break']]},
    {date:'2026-09-19',dow:'Sat',day:19,work:null,focus:'Hike / Endurance',type:'HIKE',tasks:[['5:15 AM','🐕','Quick dog walk','10–15 min'],['5:45 AM','🥣','Breakfast','Carbs + protein'],['6:30 AM','🥾','Hike / endurance','Moderate route unless fully ready'],['1:00 PM','🥗','Recovery meal','Protein + carbs + fluids'],['4:00 PM','🛋️','Recovery','Feet up + mobility'],['7:00 PM','🍽️','Dinner','Refuel']]},
    {date:'2026-09-20',dow:'Sun',day:20,work:'12:00–4:00 PM',focus:'Recovery',type:'WORK',tasks:[['6:45 AM','🐕','Dog walk','25 min'],['7:30 AM','🍳','Breakfast','Easy morning'],['8:30 AM','🧘','Mobility','20 min'],['10:30 AM','🥗','Early lunch','Before work'],['12:00 PM','🧰','Work','12:00–4:00 PM'],['5:30 PM','🚶','Recovery walk','20–30 min'],['7:00 PM','📝','Weekly review','5 min']]},
    {date:'2026-09-21',dow:'Mon',day:21,work:null,focus:'Upper + Bike',type:'OFF',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Protein + carbs'],['8:30 AM','🏋️','Upper Body A','~60 min'],['9:40 AM','🚲','Bike Zone 2','30 min'],['11:45 AM','🥗','Lunch','Recovery meal'],['1:00 PM','🧠','REBUILD dev','60 min'],['7:00 PM','🍽️','Dinner','Protein + vegetables']]},
    {date:'2026-09-22',dow:'Tue',day:22,work:'7:00 AM–3:30 PM',focus:'Easy Run 4 mi',type:'WORK',tasks:[['5:45 AM','🐕','Quick dog walk','15–20 min'],['6:10 AM','🍳','Breakfast','Before work'],['7:00 AM','🧰','Work','7:00 AM–3:30 PM'],['12:00 PM','🥗','Lunch','At work'],['4:30 PM','🍌','Pre-run snack','Easy carbs'],['5:15 PM','🏃','Easy Run','4.0 mi • conversational'],['6:15 PM','🧘','Cooldown','10 min'],['7:00 PM','🍽️','Dinner','Recovery meal']]},
    {date:'2026-09-23',dow:'Wed',day:23,work:'7:00–11:00 AM',focus:'Lower + Row',type:'WORK',tasks:[['5:45 AM','🐕','Quick dog walk','15–20 min'],['6:10 AM','🍳','Breakfast','Before work'],['7:00 AM','🧰','Work','7:00–11:00 AM'],['11:30 AM','🥗','Lunch','Pre-training'],['1:00 PM','🏋️','Lower Body','~55 min'],['2:05 PM','🚣','Row Zone 2','25–30 min'],['4:00 PM','🧠','REBUILD dev','45 min'],['7:00 PM','🍽️','Dinner','Protein + vegetables']]},
    {date:'2026-09-24',dow:'Thu',day:24,work:'9:30 AM–6:00 PM',focus:'Tempo Run',type:'WORK',tasks:[['5:55 AM','🐕','Dog walk','20 min'],['6:25 AM','🍳','Breakfast','Light + carb focused'],['7:00 AM','🏃','Tempo Run','3.5–4 mi total'],['8:00 AM','🚿','Shower + prep','Get ready for work'],['9:30 AM','🧰','Work','9:30 AM–6:00 PM'],['1:00 PM','🥗','Lunch','At work'],['7:00 PM','🍽️','Dinner','Recovery meal'],['8:00 PM','🧠','REBUILD dev','30 min • optional']]},
    {date:'2026-09-25',dow:'Fri',day:25,work:null,focus:'Full + Air Bike',type:'OFF',tasks:[['6:30 AM','🐕','Dog walk','25–30 min'],['7:15 AM','🍳','Breakfast','Protein + carbs'],['8:30 AM','🏋️','Full Body','~55 min'],['9:35 AM','🚴','Air Bike Zone 2','30 min'],['11:45 AM','🥗','Lunch','Recovery meal'],['1:00 PM','🧠','REBUILD dev','60–90 min'],['7:00 PM','🍽️','Dinner','Protein + vegetables']]},
    {date:'2026-09-26',dow:'Sat',day:26,work:'9:30 AM–6:00 PM',focus:'Recovery',type:'WORK',tasks:[['6:20 AM','🐕','Dog walk','20–25 min'],['7:00 AM','🧘','Mobility','20 min'],['7:30 AM','🍳','Breakfast','Easy morning'],['9:30 AM','🧰','Work','9:30 AM–6:00 PM'],['1:00 PM','🥗','Lunch','At work'],['7:00 PM','🍽️','Dinner','Recovery meal'],['8:00 PM','📝','Weekly notes','5 min']]},
    {date:'2026-09-27',dow:'Sun',day:27,work:null,focus:'Long Run 6 mi',type:'LONG',tasks:[['6:15 AM','🍌','Pre-run snack','Carbs + water'],['7:00 AM','🏃','Long Run','6.0 mi • easy'],['8:15 AM','🧘','Cooldown','Walk + mobility'],['8:45 AM','🍳','Breakfast','Big recovery meal'],['12:30 PM','🥗','Lunch','Protein + carbs'],['3:00 PM','🧠','REBUILD dev','Weekly cleanup'],['7:00 PM','🍽️','Dinner','Refuel'],['8:30 PM','📝','Weekly review','Mileage + wins']]}
  ],
  workouts:{
    'Upper Body A':{type:'strength',title:'Upper Body A',subtitle:'Strength + clean volume',exercises:[
      {name:'Bench Press',sets:'4 × 6',rest:'2:30',primary:'Chest',secondary:'Triceps • Front delts',cues:['Shoulder blades back and down','Feet planted','Touch lower chest','Wrists stacked over elbows'],mistakes:['Elbows flared too wide','Bouncing the bar','Losing upper-back tension'],video:'https://www.youtube.com/results?search_query=bench+press+proper+form+short'},
      {name:'1-Arm DB Row',sets:'4 × 10 / side',rest:'1:30',primary:'Lats',secondary:'Upper back • Biceps',cues:['Brace hard','Pull elbow toward hip','Pause near torso'],mistakes:['Twisting torso','Shrugging','Using momentum'],video:'https://www.youtube.com/results?search_query=one+arm+dumbbell+row+proper+form+short'},
      {name:'Overhead Press',sets:'3 × 8',rest:'2:00',primary:'Shoulders',secondary:'Triceps • Upper chest',cues:['Glutes tight','Ribs down','Bar travels close'],mistakes:['Leaning back too far','Pressing around the face','Loose core'],video:'https://www.youtube.com/results?search_query=overhead+press+proper+form+short'},
      {name:'Lat Pulldown',sets:'3 × 8–10',rest:'1:30',primary:'Lats',secondary:'Biceps • Upper back',cues:['Chest tall','Pull elbows down','Control the stretch'],mistakes:['Swinging','Pulling behind neck','Half reps'],video:'https://www.youtube.com/results?search_query=lat+pulldown+proper+form+short'},
      {name:'Lateral Raise',sets:'3 × 15',rest:'1:00',primary:'Side delts',secondary:'Upper traps',cues:['Soft elbows','Raise in scapular plane','Control down'],mistakes:['Heavy swinging','Shrugging','Hands too high'],video:'https://www.youtube.com/results?search_query=lateral+raise+proper+form+short'},
      {name:'DB Curl',sets:'3 × 12',rest:'1:00',primary:'Biceps',secondary:'Forearms',cues:['Elbows still','Full range','Slow lower'],mistakes:['Hip swing','Shoulders rolling forward','Cutting range'],video:'https://www.youtube.com/results?search_query=dumbbell+curl+proper+form+short'},
      {name:'Triceps Pressdown',sets:'3 × 12',rest:'1:00',primary:'Triceps',secondary:'Forearms',cues:['Elbows pinned','Full extension','Control return'],mistakes:['Shoulder movement','Leaning excessively','Partial reps'],video:'https://www.youtube.com/results?search_query=triceps+pressdown+proper+form+short'}
    ]},
    'Lower Body':{type:'strength',title:'Lower Body',subtitle:'Strength without wrecking the run plan',exercises:[
      {name:'Squat',sets:'4 × 6',rest:'2:30',primary:'Quads',secondary:'Glutes • Core',cues:['Brace before descent','Knees track with toes','Stay balanced mid-foot'],mistakes:['Knees collapsing in','Losing brace','Rushing depth'],video:'https://www.youtube.com/results?search_query=squat+proper+form+short'},
      {name:'Romanian Deadlift',sets:'3 × 8',rest:'2:00',primary:'Hamstrings',secondary:'Glutes • Back',cues:['Push hips back','Soft knees','Keep weight close'],mistakes:['Squatting the hinge','Rounding back','Chasing floor depth'],video:'https://www.youtube.com/results?search_query=romanian+deadlift+proper+form+short'},
      {name:'Bulgarian Split Squat',sets:'3 × 8 / leg',rest:'1:30',primary:'Quads',secondary:'Glutes',cues:['Front foot stable','Lower under control','Drive through full foot'],mistakes:['Too narrow stance','Bouncing','Knee collapsing'],video:'https://www.youtube.com/results?search_query=bulgarian+split+squat+proper+form+short'}
    ]},
    'Full Body':{type:'strength',title:'Full Body',subtitle:'Balanced volume + athletic carryover',exercises:[
      {name:'Incline DB Press',sets:'3 × 10',rest:'1:30',primary:'Upper chest',secondary:'Triceps • Front delts',cues:['Shoulders set','Control bottom','Press slightly inward'],mistakes:['Bench too steep','Elbows flared','Dropping too deep'],video:'https://www.youtube.com/results?search_query=incline+dumbbell+press+proper+form+short'},
      {name:'Chest-Supported Row',sets:'3 × 10',rest:'1:30',primary:'Upper back',secondary:'Lats • Biceps',cues:['Chest stays planted','Pull elbows back','Pause briefly'],mistakes:['Shrugging','Short reps','Jerking weight'],video:'https://www.youtube.com/results?search_query=chest+supported+row+proper+form+short'}
    ]}
  },
  history:[['Sep 4','Upper Body','Bench 135 × 6, 6, 6, 5','Completed'],['Sep 3','Easy Run','2.8 mi • 29:14','Completed'],['Sep 1','Lower Body','Squat 95 × 6, 6, 6, 6','Completed']]
};
